file_available_schema = {
    'date':'Date',
    'type':'TEXT',
    'category':'TEXT'
}
file_available_pk = ['date', 'type', 'category']

stats_schema = {
    'Player': 'Text',
    'Distanza': 'REAL',
    'Distanza /min': 'REAL',
    'Spesa Energetica': 'REAL',
    'Dist > 15 km/h': 'REAL',
    'Dist MP>20 W/Kg': 'REAL',
    '%Dist > 15km/h': 'REAL',
    '%Dist Acc>5 m/s2': 'REAL',
    '%Dist Dec<-5 m/s2': 'REAL',
    '%Dist MP>20 W/Kg': 'REAL',
    'Potenza Met': 'REAL',
    'EDRel': 'REAL',
    '%Dist Equivalente': 'REAL',
    '%Ind. Anaerobico': 'REAL',
    'Dist 0-5 km/h': 'REAL',
    'Dist 5-10 km/h': 'REAL',
    'Dist 10-15 km/h': 'REAL',
    'Dist 15-20 km/h': 'REAL',
    'Dist 20-25 km/h': 'REAL',
    'Dist > 25 km/h': 'REAL',
    'T 0-5 km/h': 'REAL',
    'T 5-10 km/h': 'REAL',
    'T 10-15 km/h': 'REAL',
    'T 15-20 km/h': 'REAL',
    'T 20-25 km/h': 'REAL',
    'T>15 km/h': 'REAL',
    'T>25 km/h': 'REAL',
    'D dec < -5 m/s2': 'INTEGER',
    'D dec < -4 m/s2': 'INTEGER',
    'D dec -4 & -3 m/s2': 'INTEGER',
    'D dec -3 & -2 m/s2': 'INTEGER',
    'D dec -2 & -1 m/s2': 'INTEGER',
    'D acc 1-2 m/s2': 'INTEGER',
    'D acc 2-3 m/s2': 'INTEGER',
    'D acc 3-4 m/s2': 'INTEGER',
    'D acc > 4 m/s2': 'INTEGER',
    'D acc > 5 m/s2': 'INTEGER',
    'T dec < -5 m/s2': 'REAL',
    'T dec < -4 m/s2': 'REAL',
    'T dec -4 & -3 m/s2': 'REAL',
    'T dec -3 & -2 m/s2': 'REAL',
    'T dec -2 & -1 m/s2': 'REAL',
    'T acc 1-2 m/s2': 'REAL',
    'T acc 2-3 m/s2': 'REAL',
    'T acc 3-4 m/s2': 'REAL',
    'T acc > 4 m/s2': 'REAL',
    'T acc > 5 m/s2': 'REAL',
    'RPE': 'REAL',  
    'T': 'REAL',  # Total time is likely to be stored as REAL for precision
    'Num Acc > 3 m/s2': 'INTEGER',
    'Num Dec <-3 m/s2': 'INTEGER',
    'SMax (kmh)': 'REAL',
    'Minutes': 'REAL',
    'date':'Date',
    'type':'TEXT',
    'category':'TEXT'
}
stats_schema_pk = ['Player','date', 'type', 'category']